### ISSUE TITLE
可否来个ssrplus

### ISSUE THREAD

**Issue by facerleo** [281677160/openwrt-package#20]

**Comment by 281677160** [comment]
呃，不需要，我配套仓库自带了，如果不是用我仓库就自己拉一下就好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/openwrt-package"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月6日(星期五) 凌晨0:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[281677160/openwrt-package] 可否来个ssrplus (#20)





 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 281677160** [comment]
我的插件包都脱离了插件意思了，我很多要替换的文件或者依赖什么的我都放这里的，在主体编译的时候会先删除要替换的文件再把这些覆盖进去，如果不删除再覆盖容易出现编译错误，所以我不太建议别人使用我的插件包
