### ISSUE TITLE
拉取单独插件问题！

### ISSUE THREAD

**Issue by sjkhsl** [281677160/openwrt-package#21]
按照说明文档将原链接改为
svn co https://github.com/281677160/openwrt-package/master/feeds/luci/applications/luci-app-netdata
并不能拉去，提示错误。实验了一下
svn co https://github.com/281677160/openwrt-package/master/luci-app-netdata
也不行。然后试验git clone -b master 也失败了~
拉取lede的，因该就是使用master啊。路径还有什么问题吗？

**Comment by 281677160** [comment]
svn co&nbsp;https://github.com/281677160/openwrt-package/master/feeds/luci/applications/luci-app-netdata&nbsp;后面要带存放路径
拉取默认分支的时候要把tree/master 或者tree/main 之类的修改成trunk，正确链接应该是


svn co https://github.com/281677160/openwrt-package/trunk/feeds/luci/applications/luci-app-netdata 你自己看看有什么不一样？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/openwrt-package"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月10日(星期二) 下午4:59
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[281677160/openwrt-package] 拉取单独插件问题！ (#21)





 
按照说明文档将原链接改为
 svn co https://github.com/281677160/openwrt-package/master/feeds/luci/applications/luci-app-netdata
 并不能拉去，提示错误。实验了一下
 svn co https://github.com/281677160/openwrt-package/master/luci-app-netdata
 也不行。然后试验git clone -b master 也失败了~
 拉取lede的，因该就是使用master啊。路径还有什么问题吗？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
