### ISSUE TITLE
能否支持官方源码

### ISSUE THREAD

**Issue by hululu1068** [281677160/openwrt-package#22]

**Comment by 281677160** [comment]
大部分插件都支持官方的，用的时候改一下语言包就可以了，要不然编译出来是英文的，因为我压根就没想过玩官方的，所以我就不搞了，有那么多大神弄源码，干嘛要去搞官方的坑




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/openwrt-package"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月4日(星期六) 下午5:06
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[281677160/openwrt-package] 能否支持官方源码 (#22)





 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
