### ISSUE TITLE
lienol新版r22.03版本的luci-app-frpc很难用，可以替换为lede的版本么？

### ISSUE THREAD

**Issue by lee29** [281677160/openwrt-package#27]
我在diy-part.sh中添加svn co https://github.com/coolsnowwolf/packages/trunk/net/frp package/net/frp 

svn co https://github.com/coolsnowwolf/luci/trunk/applications/luci-app-frpc package/applications/luci-app-frpc

在编译是显示信息
Collecting target info: doneWARNING: Not overriding core package 'frp'; use -f to force

WARNING: Not overriding core package 'luci-app-frpc'; use -f to force

WARNING: Not overriding core package 'luci-app-frpc'; use -f to force

进入make menuconfig时luci-app-frpc选项直接没了。求教~~~

**Comment by 281677160** [comment]
已经替换成大雕的了，你编译了测试一下吧，呃，这个只有我仓库编译才是替换的，只用我插件包的话，替换不了的

**Comment by 281677160** [comment]
替换成大雕的没用，编译完成后，LUCI错误

**Comment by lee29** [comment]
> 替换成大雕的没用，编译完成后，LUCI错误

我用大雕的ipk安装试过没问题的，是luci版本校验的问题么

**Comment by lee29** [comment]
还有一个我想添加一个插件 https://github.com/Hyy2001X/AutoBuild-Packages/tree/master/luci-app-webd
应该怎么加进去，只能你这边仓库收录了才可以么，以前的在diy-part.sh添加git clone好像不行了，ssh进去make menuconfig时可以选到插件，但在      正式编译-已选插件列表  下面没有了

**Comment by 281677160** [comment]
添加链接要弄对，还有就是你没拉主程序，就拉了个LUCI的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/openwrt-package"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月22日(星期五) 凌晨1:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [281677160/openwrt-package] lienol新版r22.03版本的luci-app-frpc很难用，可以替换为lede的版本么？ (Issue #27)





 
还有一个我想添加一个插件 https://github.com/Hyy2001X/AutoBuild-Packages/tree/master/luci-app-webd
 应该怎么加进去，只能你这边仓库收录了才可以么，以前的在diy-part.sh添加git clone好像不行了，ssh进去make menuconfig时可以选到插件，但在      正式编译-已选插件列表  下面没有了

**Comment by lee29** [comment]
> 添加链接要弄对，还有就是你没拉主程序，就拉了个LUCI的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/openwrt-package" ***@***.***&gt;; 发送时间:&nbsp;2022年4月22日(星期五) 凌晨1:56 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [281677160/openwrt-package] lienol新版r22.03版本的luci-app-frpc很难用，可以替换为lede的版本么？ (Issue #27) 还有一个我想添加一个插件 https://github.com/Hyy2001X/AutoBuild-Packages/tree/master/luci-app-webd 应该怎么加进去，只能你这边仓库收录了才可以么，以前的在diy-part.sh添加git clone好像不行了，ssh进去make menuconfig时可以选到插件，但在 正式编译-已选插件列表 下面没有了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

ok了，我用的是echo "src-git webd https://github.com/lee29/webd" >> "$HOME_PATH/feeds.conf.default"

**Comment by lee29** [comment]
> 添加链接要弄对，还有就是你没拉主程序，就拉了个LUCI的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/openwrt-package" ***@***.***&gt;; 发送时间:&nbsp;2022年4月22日(星期五) 凌晨1:56 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [281677160/openwrt-package] lienol新版r22.03版本的luci-app-frpc很难用，可以替换为lede的版本么？ (Issue #27) 还有一个我想添加一个插件 https://github.com/Hyy2001X/AutoBuild-Packages/tree/master/luci-app-webd 应该怎么加进去，只能你这边仓库收录了才可以么，以前的在diy-part.sh添加git clone好像不行了，ssh进去make menuconfig时可以选到插件，但在 正式编译-已选插件列表 下面没有了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

luci-app-frpc这个问题可以解决么

**Comment by 281677160** [comment]
你都没拉他的程序，不过没所谓了，我插件包添加了，你都不需要拉了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/openwrt-package"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月22日(星期五) 凌晨2:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [281677160/openwrt-package] lienol新版r22.03版本的luci-app-frpc很难用，可以替换为lede的版本么？ (Issue #27)





  
添加链接要弄对，还有就是你没拉主程序，就拉了个LUCI的
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/openwrt-package" @.&gt;; 发送时间:&nbsp;2022年4月22日(星期五) 凌晨1:56 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [281677160/openwrt-package] lienol新版r22.03版本的luci-app-frpc很难用，可以替换为lede的版本么？ (Issue #27) 还有一个我想添加一个插件 https://github.com/Hyy2001X/AutoBuild-Packages/tree/master/luci-app-webd 应该怎么加进去，只能你这边仓库收录了才可以么，以前的在diy-part.sh添加git clone好像不行了，ssh进去make menuconfig时可以选到插件，但在 正式编译-已选插件列表 下面没有了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
ok了，我用的是echo "src-git webd https://github.com/lee29/webd" &gt;&gt; "$HOME_PATH/feeds.conf.default"

**Comment by 281677160** [comment]
直接拉大雕的，LUCI错误，编译了也用不了，你可以去测试一下天灵的21.02的看看，如果他的好用，换他的来到22.03或者可以用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/openwrt-package"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月22日(星期五) 凌晨2:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [281677160/openwrt-package] lienol新版r22.03版本的luci-app-frpc很难用，可以替换为lede的版本么？ (Issue #27)





  
添加链接要弄对，还有就是你没拉主程序，就拉了个LUCI的
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/openwrt-package" @.&gt;; 发送时间:&nbsp;2022年4月22日(星期五) 凌晨1:56 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [281677160/openwrt-package] lienol新版r22.03版本的luci-app-frpc很难用，可以替换为lede的版本么？ (Issue #27) 还有一个我想添加一个插件 https://github.com/Hyy2001X/AutoBuild-Packages/tree/master/luci-app-webd 应该怎么加进去，只能你这边仓库收录了才可以么，以前的在diy-part.sh添加git clone好像不行了，ssh进去make menuconfig时可以选到插件，但在 正式编译-已选插件列表 下面没有了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
luci-app-frpc这个问题可以解决么

**Comment by lee29** [comment]
天灵的21.02的https://github.com/immortalwrt/luci/blob/openwrt-21.02/applications/luci-app-frpc/po/zh_Hans/frpc.po
他是新版本的，和lienol的一样，都不是旧版

**Comment by lee29** [comment]
目前看来只有大雕的保持了旧版本
